USE [master]
GO

/****** Object:  Database [BD_Produtos]    Script Date: 21/05/2025 20:47:23 ******/
CREATE DATABASE [BD_Produtos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Produtos', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Produtos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Produtos_log', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Produtos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Produtos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Produtos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Produtos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Produtos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Produtos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Produtos] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Produtos] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BD_Produtos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Produtos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Produtos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Produtos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Produtos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Produtos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Produtos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Produtos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Produtos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BD_Produtos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Produtos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Produtos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Produtos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Produtos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Produtos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Produtos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Produtos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Produtos] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Produtos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Produtos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Produtos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Produtos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_Produtos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Produtos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_Produtos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_Produtos] SET  READ_WRITE 
GO


