/*
Criar um banco com informações de outro PC 
>> Tarefas > Gerar Scripts 

Apenas de uma tabela
>> Tabela > Script de Tabela como > ...

*/

USE [master]
GO
/****** Object:  Database [BD_Loja]    Script Date: 15/05/2025 20:46:04 ******/
CREATE DATABASE [BD_Loja]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Loja', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Loja.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Loja_log', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Loja_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BD_Loja] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Loja].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_Loja] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_Loja] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_Loja] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_Loja] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_Loja] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_Loja] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_Loja] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_Loja] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_Loja] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_Loja] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_Loja] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_Loja] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_Loja] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_Loja] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_Loja] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BD_Loja] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_Loja] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_Loja] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_Loja] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_Loja] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_Loja] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_Loja] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_Loja] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BD_Loja] SET  MULTI_USER 
GO
ALTER DATABASE [BD_Loja] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_Loja] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_Loja] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_Loja] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_Loja] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BD_Loja] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BD_Loja] SET QUERY_STORE = OFF
GO
USE [BD_Loja]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[IdCategoria] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Categorias] PRIMARY KEY CLUSTERED 
(
	[IdCategoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[IdCLiente] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](70) NOT NULL,
	[Cpf] [varchar](14) NOT NULL,
	[Email] [varchar](70) NOT NULL,
	[Telefone] [varchar](15) NULL,
	[Endereco] [varchar](100) NOT NULL,
	[Nro] [varchar](10) NOT NULL,
	[Complemento] [nchar](50) NULL,
	[Bairro] [varchar](50) NOT NULL,
	[Cidade] [varchar](47) NOT NULL,
	[UF] [varchar](2) NOT NULL,
	[DataNascimento] [datetime] NOT NULL,
	[Senha] [varchar](8) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[IdCLiente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PedidoProdutos]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PedidoProdutos](
	[IdPedidoProdutos] [int] IDENTITY(1,1) NOT NULL,
	[IdPedidos] [int] NOT NULL,
	[IdProdutos] [int] NOT NULL,
	[Quantidade] [int] NOT NULL,
	[Preco] [money] NULL,
 CONSTRAINT [PK_PedidoProdutos] PRIMARY KEY CLUSTERED 
(
	[IdPedidoProdutos] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedidos]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedidos](
	[IdPedido] [int] IDENTITY(1,1) NOT NULL,
	[IdCliente] [int] NOT NULL,
	[DataPedido] [datetime] NOT NULL,
	[ValorTotal] [money] NOT NULL,
	[Observacao] [varchar](200) NULL,
	[IdStatusPedido] [int] NOT NULL,
 CONSTRAINT [PK_Pedidos] PRIMARY KEY CLUSTERED 
(
	[IdPedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produtos]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produtos](
	[IdProdutos] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](70) NOT NULL,
	[Imagem] [varchar](200) NULL,
	[Preco] [money] NOT NULL,
	[IdCategoria] [int] NOT NULL,
 CONSTRAINT [PK_Produtos] PRIMARY KEY CLUSTERED 
(
	[IdProdutos] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StatusPedido]    Script Date: 15/05/2025 20:46:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StatusPedido](
	[IdStatusPedido] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](20) NOT NULL,
 CONSTRAINT [PK_StatusPedido] PRIMARY KEY CLUSTERED 
(
	[IdStatusPedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PedidoProdutos]  WITH CHECK ADD  CONSTRAINT [FK_PedidoProdutos_Pedidos] FOREIGN KEY([IdPedidos])
REFERENCES [dbo].[Pedidos] ([IdPedido])
GO
ALTER TABLE [dbo].[PedidoProdutos] CHECK CONSTRAINT [FK_PedidoProdutos_Pedidos]
GO
ALTER TABLE [dbo].[PedidoProdutos]  WITH CHECK ADD  CONSTRAINT [FK_PedidoProdutos_Produtos] FOREIGN KEY([IdProdutos])
REFERENCES [dbo].[Produtos] ([IdProdutos])
GO
ALTER TABLE [dbo].[PedidoProdutos] CHECK CONSTRAINT [FK_PedidoProdutos_Produtos]
GO
ALTER TABLE [dbo].[Pedidos]  WITH CHECK ADD  CONSTRAINT [FK_Pedidos_Cliente] FOREIGN KEY([IdCliente])
REFERENCES [dbo].[Cliente] ([IdCLiente])
GO
ALTER TABLE [dbo].[Pedidos] CHECK CONSTRAINT [FK_Pedidos_Cliente]
GO
ALTER TABLE [dbo].[Pedidos]  WITH CHECK ADD  CONSTRAINT [FK_Pedidos_StatusPedido] FOREIGN KEY([IdStatusPedido])
REFERENCES [dbo].[StatusPedido] ([IdStatusPedido])
GO
ALTER TABLE [dbo].[Pedidos] CHECK CONSTRAINT [FK_Pedidos_StatusPedido]
GO
ALTER TABLE [dbo].[Produtos]  WITH CHECK ADD  CONSTRAINT [FK_Produtos_Categorias] FOREIGN KEY([IdCategoria])
REFERENCES [dbo].[Categorias] ([IdCategoria])
GO
ALTER TABLE [dbo].[Produtos] CHECK CONSTRAINT [FK_Produtos_Categorias]
GO
USE [master]
GO
ALTER DATABASE [BD_Loja] SET  READ_WRITE 
GO
