USE [master]
GO
/****** Object:  Database [BD_Palmirinha]    Script Date: 15/05/2025 22:10:57 ******/
CREATE DATABASE [BD_Palmirinha]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Palmirinha', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Palmirinha.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Palmirinha_log', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Palmirinha_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BD_Palmirinha] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Palmirinha].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_Palmirinha] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BD_Palmirinha] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_Palmirinha] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_Palmirinha] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BD_Palmirinha] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_Palmirinha] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BD_Palmirinha] SET  MULTI_USER 
GO
ALTER DATABASE [BD_Palmirinha] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_Palmirinha] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_Palmirinha] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_Palmirinha] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_Palmirinha] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BD_Palmirinha] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BD_Palmirinha] SET QUERY_STORE = OFF
GO
USE [BD_Palmirinha]
GO
/****** Object:  Table [dbo].[Avaliacao]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Avaliacao](
	[IdAvaliacao] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[IdReceita] [int] NOT NULL,
	[Nota] [tinyint] NULL,
	[Comentario] [varchar](1000) NOT NULL,
	[Data] [date] NULL,
 CONSTRAINT [PK__Avaliaca__78C432D83E61448C] PRIMARY KEY CLUSTERED 
(
	[IdAvaliacao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GrauDificuldade]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrauDificuldade](
	[IdGrauDificuldade] [int] NOT NULL,
	[Nome] [varchar](15) NOT NULL,
 CONSTRAINT [PK__GrauDifi__4017E8E423DD9457] PRIMARY KEY CLUSTERED 
(
	[IdGrauDificuldade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ingrediente]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingrediente](
	[IdIngrediente] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[PrecoSugerido] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK__Ingredie__3DA4DD605EDBD345] PRIMARY KEY CLUSTERED 
(
	[IdIngrediente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IngredienteLoja]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IngredienteLoja](
	[IdIngredienteLoja] [int] IDENTITY(1,1) NOT NULL,
	[IdIngrediente] [int] NOT NULL,
	[IdLoja] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdIngredienteLoja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loja]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loja](
	[IdLoja] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Logradouro] [varchar](100) NOT NULL,
	[Nro] [varchar](10) NOT NULL,
	[Complemento] [varchar](50) NULL,
	[Bairro] [varchar](50) NOT NULL,
	[Cidade] [varchar](50) NOT NULL,
	[Uf] [varchar](2) NOT NULL,
	[Cep] [varchar](9) NOT NULL,
	[Cnpj] [varchar](18) NOT NULL,
	[Telefone] [varchar](14) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLoja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Receita]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Receita](
	[IdReceita] [int] NOT NULL,
	[IdGrauDificuldade] [int] NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[TempoPreparo] [int] NOT NULL,
	[ModoPreparo] [varchar](8000) NOT NULL,
	[QtdePorcoes] [tinyint] NOT NULL,
 CONSTRAINT [PK__Receita__27290E9A37839ECB] PRIMARY KEY CLUSTERED 
(
	[IdReceita] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReceitaIngrediente]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReceitaIngrediente](
	[IdReceitaIngrediente] [int] NOT NULL,
	[IdReceita] [int] NOT NULL,
	[IdIngrediente] [int] NOT NULL,
	[Qtde] [int] NOT NULL,
 CONSTRAINT [PK__ReceitaI__0AF02B3C5C1AFE86] PRIMARY KEY CLUSTERED 
(
	[IdReceitaIngrediente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
 CONSTRAINT [PK__Usuario__5B65BF97CF55753E] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsuarioAcesso]    Script Date: 15/05/2025 22:10:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioAcesso](
	[IdUsuario] [int] NOT NULL,
	[Login] [varchar](20) NOT NULL,
	[Senha] [varchar](50) NOT NULL,
	[Bloqueado] [bit] NOT NULL,
 CONSTRAINT [PK__UsuarioA__5B65BF97146138E4] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Avaliacao]  WITH CHECK ADD  CONSTRAINT [FK__Avaliacao__IdRec__4F7CD00D] FOREIGN KEY([IdReceita])
REFERENCES [dbo].[Receita] ([IdReceita])
GO
ALTER TABLE [dbo].[Avaliacao] CHECK CONSTRAINT [FK__Avaliacao__IdRec__4F7CD00D]
GO
ALTER TABLE [dbo].[Avaliacao]  WITH CHECK ADD  CONSTRAINT [FK__Avaliacao__IdUsu__4E88ABD4] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Avaliacao] CHECK CONSTRAINT [FK__Avaliacao__IdUsu__4E88ABD4]
GO
ALTER TABLE [dbo].[IngredienteLoja]  WITH CHECK ADD  CONSTRAINT [FK__Ingredien__IdIng__3A81B327] FOREIGN KEY([IdIngrediente])
REFERENCES [dbo].[Ingrediente] ([IdIngrediente])
GO
ALTER TABLE [dbo].[IngredienteLoja] CHECK CONSTRAINT [FK__Ingredien__IdIng__3A81B327]
GO
ALTER TABLE [dbo].[IngredienteLoja]  WITH CHECK ADD FOREIGN KEY([IdLoja])
REFERENCES [dbo].[Loja] ([IdLoja])
GO
ALTER TABLE [dbo].[Receita]  WITH CHECK ADD  CONSTRAINT [FK__Receita__IdGrauD__4316F928] FOREIGN KEY([IdGrauDificuldade])
REFERENCES [dbo].[GrauDificuldade] ([IdGrauDificuldade])
GO
ALTER TABLE [dbo].[Receita] CHECK CONSTRAINT [FK__Receita__IdGrauD__4316F928]
GO
ALTER TABLE [dbo].[ReceitaIngrediente]  WITH CHECK ADD  CONSTRAINT [FK__ReceitaIn__IdIng__46E78A0C] FOREIGN KEY([IdIngrediente])
REFERENCES [dbo].[Ingrediente] ([IdIngrediente])
GO
ALTER TABLE [dbo].[ReceitaIngrediente] CHECK CONSTRAINT [FK__ReceitaIn__IdIng__46E78A0C]
GO
ALTER TABLE [dbo].[ReceitaIngrediente]  WITH CHECK ADD  CONSTRAINT [FK__ReceitaIn__IdRec__45F365D3] FOREIGN KEY([IdReceita])
REFERENCES [dbo].[Receita] ([IdReceita])
GO
ALTER TABLE [dbo].[ReceitaIngrediente] CHECK CONSTRAINT [FK__ReceitaIn__IdRec__45F365D3]
GO
ALTER TABLE [dbo].[UsuarioAcesso]  WITH CHECK ADD  CONSTRAINT [FK__UsuarioAc__IdUsu__4BAC3F29] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[UsuarioAcesso] CHECK CONSTRAINT [FK__UsuarioAc__IdUsu__4BAC3F29]
GO
USE [master]
GO
ALTER DATABASE [BD_Palmirinha] SET  READ_WRITE 
GO
