USE [master]
GO

/****** Object:  Database [BD_Palmirinha]    Script Date: 15/05/2025 22:04:47 ******/
CREATE DATABASE [BD_Palmirinha]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Palmirinha', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Palmirinha.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Palmirinha_log', FILENAME = N'C:\Users\jonathan.ssantos22\BD_Palmirinha_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Palmirinha].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Palmirinha] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BD_Palmirinha] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Palmirinha] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Palmirinha] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BD_Palmirinha] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Palmirinha] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Palmirinha] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Palmirinha] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Palmirinha] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Palmirinha] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Palmirinha] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_Palmirinha] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Palmirinha] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_Palmirinha] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_Palmirinha] SET  READ_WRITE 
GO

